name: Check Actor Permissions
description: Check if an actor has a specific access to the repository
author: "prince-chrismc"
branding:
  icon: "check"
  color: "green"
outputs:
  permitted:
    description: "Set 'true' or 'false' depending on actor permission meeting the requirement"
inputs:
  github_token:
    description: A GitHub token.
    required: false
    default: ${{ github.token }}
  permission:
    description: The minimum permission level required
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
