name: Repo Permission Check Action
description: Check if a user has specific access to this repo
author: "Benjamin Lanon <benjamin@lannonbr.com>"
outputs:
  permitted:
    description: "'true' or 'false' depending on actor permission meeting the requirement"
inputs:
  github_token:
    description: A GitHub token.
    required: true
  permission:
    description: the minimum permission level required
    required: true
  fail:
    description: fail the job if the minimum permission level it not meet
    required: false
    default: "true"
runs:
  using: "node12"
  main: "lib/index.js"
branding:
  icon: "check"
  color: "green"
