name: Repo Permission Check Action
description: Check if a user has specific access to this repo
author: "Benjamin Lanon <benjamin@lannonbr.com>"
inputs:
  permission:
    description: the max permission level required
    required: true
runs:
  using: "node12"
  main: "lib/index.js"
branding:
  icon: "check"
  color: "green"
